# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6efd42d791905639951a2f35475e39f11aec117d5d57d6a3f52c745e82410f1850342ece1eed3418dc4346c8ad7185a79f7e0f25511f42ceb35c7a35e7ca77cb

test:
  secret_key_base: 361124d0b27a10266bff57105e127973bbf0d405ca06c3ff7db38cdbc08a64827c85b2491ca781b7da661885c2fbb5767ba5430a0ffd4e2dedd53c157da79a2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
